In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time

## for MAC, use mps while cuda not available

# device = "cuda" if torch.cuda.is_available() else "cpu"
device = "mps" if torch.backends.mps.is_available() and torch.backends.mps.is_built() else device

print(device)

mps


In [2]:
%%time

start_time = time.time()

# matrix operation here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f'{elapsed_time: .4f}')

 0.0074
CPU times: user 1.43 ms, sys: 4.39 ms, total: 5.82 ms
Wall time: 7.64 ms


In [3]:
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)

np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
# print(rand)

end_time = time.time()

elapsed_time = end_time - start_time
print(f'MPS way: {elapsed_time: 8f}')

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()
elapsed_time = end_time - start_time

print(f'Numpy way: {elapsed_time: 8f}')

MPS way:  0.407085
Numpy way:  0.539559


/var/folders/jw/mplyqmgs7_q30_k880vm8jjm0000gn/T/ipykernel_4634/321093521.py:17: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [4]:
## torch stock, torch multinomial, torch trill intput.T/input transpose, nn linear, torch cat, torch softmax
## (show all the examples of functions/methods with pytorch docs)

## Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])

## 10% or 0.1 => 0, 90% or 0.9 => 1 each probability points to the index of the probability in the tensor
## Draw 5 samples from the multinominal distribution

samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)

tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 1])


In [5]:
tensor = torch.tensor([1,2,3,4])
out    = torch.cat((tensor, torch.tensor([5])), dim=0) ## concatenate 2 tensors to 1
out

tensor([1, 2, 3, 4, 5])

In [6]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [7]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [8]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [9]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [10]:
input = torch.zeros(2,3,4)
out   = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [11]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

# Stack the tensors along a new dimension

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])

stacked_tensor                             

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
x = torch.tensor([-.05], dtype=torch.float32)
y = nn.ReLU(x)
z = F.sigmoid(x)
a = F.tanh(x)
print(y)
print(z)
print(a)

ReLU(inplace=True)
tensor([0.4875])
tensor([-0.0500])
