In [5]:
## https://pytorch.org/docs/stable/nn.html

'''
A sequential container.

Modules will be added to it in the order they are passed in the constructor. 
Alternatively, an OrderedDict of modules can be passed in. The forward() method of Sequential accepts any input and forwards it to the first module 
it contains. It then “chains” outputs to inputs sequentially for each subsequent module, finally returning the output of the last module.

The value a Sequential provides over manually calling a sequence of modules is that it allows treating the whole container 
as a single module, such that performing a transformation on the Sequential applies to each of the modules it stores 
(which are each a registered submodule of the Sequential).

What’s the difference between a Sequential and a torch.nn.ModuleList? 
A ModuleList is exactly what it sounds like–a list for storing Module s! On the other hand, 
the layers in a Sequential are connected in a cascading way.
'''

## nn.module contains any learnable parameters

import torch
import torch.nn as nn

sample = torch.tensor([10. ,10. ,10.])
linear = nn.Linear(3, 3, bias=False)

print(linear)
print(linear(sample))

Linear(in_features=3, out_features=3, bias=False)
tensor([-7.6802, -5.7228, -1.9343], grad_fn=<SqueezeBackward4>)


In [17]:
import torch.nn.functional as F

# Create tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.ff.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

# https://en.wikipedia.org/wiki/Softmax_function

tensor([0.0900, 0.2447, 0.6652])


In [22]:
# Embedding study

vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1,5,3,2])

# Apply the embedding layer
embededd_output = embedding(input_indices)

print(embededd_output.shape) # 4x100 (# of inputs x dimensionality of embedded vectors)
print(embededd_output)

torch.Size([4, 6])
tensor([[-0.2960, -1.0859,  0.0336,  0.5119, -1.0239,  0.0197],
        [ 0.4839,  0.5091,  0.3866, -0.7758,  0.2409,  1.2001],
        [-0.6070,  0.1381,  0.0581,  0.3156,  0.8762,  0.0713],
        [ 0.9854,  0.4794,  0.1359,  1.2583, -0.1617, -0.0395]],
       grad_fn=<EmbeddingBackward0>)


In [25]:
int_64 = torch.randint(1, (3,2)).float()
float_32 = torch.rand(2, 3)
print(float_32)

tensor([[0.9391, 0.1601, 0.7775],
        [0.1229, 0.0304, 0.3234]])
